WEBBPMNEXT-8997: change processId
Micord/kogito-tools pull request #6
Opened 2024-01-29 09:39 UTC by AivazNurgaliev

Теперь при вызове конструктора setId в DiagramSet еще и обновляется глобальная переменная parent.parent.processId через нативный метод.

2024-01-30 09:00 UTC, EOlegovich approved these changes

2024-01-31 06:45 UTC, EOlegovich requested changes

2024-01-31 06:45 UTC, EOlegovich commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/DiagramSet.java
> +    public static native void updateParentProcessId(String processId)/*-{
test

2024-01-31 06:45 UTC, kochetkovSergeY requested changes

2024-01-31 06:45 UTC, kochetkovSergeY commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/DiagramSet.java
> +    public static native void updateParentProcessId(String processId)/*-{
updateEditirPorcessId

2024-01-31 06:45 UTC, kochetkovSergeY commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/DiagramSet.java
> +        if (parent !== undefined &&
if (parent && parent.parent && parent.parent.processId){
 bla bla
}

2024-01-31 07:44 UTC, AivazNurgaliev commented
http://teamcity.asd.center.cg:8111/buildConfiguration/WebBpm_Jbpm_BuildKogitoRuntime/794448?buildTab=overview&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=false

После исправления замечаний запустил сборку в тимсити и протестировал, все успешно

2024-01-31 11:04 UTC, sofit approved these changes

2024-01-31 11:49 UTC, kochetkovSergeY approved these changes

2024-01-31 11:49 UTC, merged